ALTER TABLE `sale_invoice`
    ADD COLUMN `rate_type` VARCHAR(20) NULL DEFAULT NULL AFTER `bilty_no`,
    ADD COLUMN `brokery_rate_type` VARCHAR(20) NULL DEFAULT NULL AFTER `rate_type`,
    ADD COLUMN `brokery_pct_mode` TINYINT(1) NOT NULL DEFAULT 0 AFTER `brokery_rate_type`,
    ADD COLUMN `brokery_rate` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `brokery_pct_mode`,
    ADD COLUMN `brokery_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `brokery_rate`,
    ADD COLUMN `brokery_tax_percent` DECIMAL(8,2) NOT NULL DEFAULT 0.00 AFTER `brokery_amount`,
    ADD COLUMN `brokery_tax_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `brokery_tax_percent`,
    ADD COLUMN `wt_charges` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `brokery_tax_amount`,
    ADD COLUMN `wt_charges_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `wt_charges`,
    ADD COLUMN `freight` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `wt_charges_sign`,
    ADD COLUMN `freight_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `freight`,
    ADD COLUMN `m_sukri` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `freight_sign`,
    ADD COLUMN `m_sukri_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `m_sukri`,
    ADD COLUMN `broken_amount_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `m_sukri_sign`,
    ADD COLUMN `brokery_amount_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `broken_amount_sign`,
    ADD COLUMN `brokery_tax_amount_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `brokery_amount_sign`,
    ADD COLUMN `bardana` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `brokery_tax_amount_sign`,
    ADD COLUMN `bardana_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `bardana`,
    ADD COLUMN `phone_charges` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `bardana_sign`,
    ADD COLUMN `phone_charges_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `phone_charges`,
    ADD COLUMN `filling_charges` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `phone_charges_sign`,
    ADD COLUMN `filling_charges_sign` CHAR(1) NOT NULL DEFAULT '+' AFTER `filling_charges`,
    ADD COLUMN `total_charges` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `filling_charges_sign`;
