ALTER TABLE `sale_invoice_items`
    ADD COLUMN `bag` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `uom_id`,
    ADD COLUMN `total_kg` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `bag`,
    ADD COLUMN `cut_kg_percent` DECIMAL(8,2) NOT NULL DEFAULT 0.00 AFTER `total_kg`,
    ADD COLUMN `cut_kg` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `cut_kg_percent`,
    ADD COLUMN `al_kg_percent` DECIMAL(8,2) NOT NULL DEFAULT 0.00 AFTER `cut_kg`,
    ADD COLUMN `al_kg` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `al_kg_percent`,
    ADD COLUMN `net_kg` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `al_kg`,
    ADD COLUMN `al_rate_cut` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `net_kg`,
    ADD COLUMN `net_rate` DECIMAL(15,2) NOT NULL DEFAULT 0.00 AFTER `al_rate_cut`;
