<?php
require_once '../../../../includes/dashboard.php';
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
$user_id = $_SESSION['user_id'] ?? null;
if (!$user_id) {
    header('Location: ../../auth/login.html');
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FuelingSys - Petrol Daily Sale Sheet</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="../../../assets/css/sale/meter_invoice/worksheet-invoice.css">
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <div class="title-section">
                <h1>Diesel Daily Sale Sheet</h1>
                <p>Daily meter readings for diesel sales tracking (Combined for all stations)</p>
            </div>
            <div class="actions">
                <button class="btn btn-secondary" id="clearBtn">
                    <i class="fas fa-eraser"></i> Clear All
                </button>
                <button class="btn btn-primary" id="saveBtn">
                    <i class="fas fa-save"></i> Save Worksheet
                </button>
                <button class="btn btn-ghost" id="printBtn" onclick="window.open('worksheet-print-hsd.php', '_blank')">
                    <i class="fas fa-print"></i> Print
                </button>
            </div>
        </div>

        <!-- Worksheet -->
        <div class="worksheet-container">
            <div class="worksheet-info">
                <div>
                    <span id="totalEntries">30 entries</span> per page. Page <span id="currentPage">1</span> of <span id="totalPages">1</span>
                </div>
                <div class="pagination-controls">
                    <button class="btn btn-secondary" id="prevPageBtn" disabled>
                        <i class="fas fa-chevron-left"></i> Previous
                    </button>
                    <span class="page-info">Page <span id="pageNumber">1</span></span>
                    <button class="btn btn-secondary" id="nextPageBtn">
                        Next <i class="fas fa-chevron-right"></i>
                    </button>
                </div>
            </div>

            <table class="worksheet-table" id="worksheetTable">
                <thead>
                    <tr>
                        <th style="width: 120px;">Date</th>
                        <th style="width: 150px;">Opening Meter</th>
                        <th style="width: 150px;">Closing Meter</th>
                        <th style="width: 120px;">Ltr</th>
                        <th style="width: 120px;">Rate</th>
                        <th style="width: 150px;">Amount (Ltr * Rate)</th>
                        <th style="width: 80px;">Actions</th>
                    </tr>
                </thead>
                <tbody id="worksheetBody">
                    <!-- Rows will be generated by JavaScript -->
                </tbody>
            </table>
        </div>

        <!-- Footer -->
        <div class="footer">
            <div class="summary">
                <div class="summary-item">
                    <span class="summary-label">Total Liters</span>
                    <span class="summary-value" id="totalLiters">0.00</span>
                </div>
                <div class="summary-item">
                    <span class="summary-label">Total Amount</span>
                    <span class="summary-value" id="totalAmount">$0.00</span>
                </div>
                <div class="summary-item">
                    <span class="summary-label">Avg. Rate</span>
                    <span class="summary-value" id="avgRate">$0.00</span>
                </div>
            </div>
            <div class="actions">
                <button class="btn btn-primary" id="addRowBtn">
                    <i class="fas fa-plus"></i> Add Row
                </button>
            </div>
        </div>
    </div>

    <script>
        // Hardcoded values - must be set before loading worksheet-invoice.js
        window.HARDCODED_PRODUCT_ID = 5;
        window.HARDCODED_BRANCH_ID = 4;
        window.HARDCODED_UNIT_ID = 7;
        window.HARDCODED_STATION_ID = 3;
    </script>
    <script src="../../../assets/js/sale/meter_invoice/worksheet-invoice.js"></script>
</body>
</html>