ALTER TABLE suppliers ADD COLUMN is_sales_tax_registered TINYINT(1) DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN strn VARCHAR(50) NULL;
ALTER TABLE suppliers ADD COLUMN is_filer TINYINT(1) DEFAULT 0;
ALTER TABLE suppliers ADD COLUMN ntn VARCHAR(50) NULL;
