<?php
require_once '../../../../includes/connection.php';
session_start();

$user_id = $_SESSION['user_id'] ?? null;
$tenant_id = $_SESSION['tenant_id'] ?? null;

if (!$user_id || !$tenant_id) {
    header('Location: ../../auth/login.html');
    exit();
}

// Get currency symbol
$stmt = $pdo->prepare("SELECT c.symbol FROM tenant_currencies tc JOIN ledgerone_public.currencies c ON tc.currency_id = c.id WHERE tc.tenant_id = ? AND tc.is_base_currency = 1");
$stmt->execute([$tenant_id]);
$currency = $stmt->fetch();
$currency_symbol = $currency['symbol'] ?? '$';

$report_type = $_GET['type'] ?? 'item';
$date_range = $_GET['date_range'] ?? 'last30';
$company_id = $_GET['company_id'] ?? null;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Report - Print</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            padding: 20px;
            color: #333;
        }

        .print-header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }

        .print-header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }

        .print-header p {
            font-size: 14px;
            color: #666;
        }

        .report-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            font-size: 12px;
        }

        .report-info div {
            flex: 1;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }

        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }

        .print-footer {
            margin-top: 30px;
            text-align: center;
            font-size: 11px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        @media print {
            body {
                padding: 0;
            }
            
            .no-print {
                display: none;
            }

            @page {
                margin: 1cm;
            }
        }
    </style>
</head>
<body>
    <div class="print-header">
        <h1>Purchase Report</h1>
        <p id="reportTitle">Loading...</p>
    </div>

    <div class="report-info">
        <div>
            <strong>Report Type:</strong> <span id="reportType"></span>
        </div>
        <div>
            <strong>Date Range:</strong> <span id="dateRange"></span>
        </div>
        <div>
            <strong>Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?>
        </div>
    </div>

    <table id="reportTable">
        <thead id="tableHead"></thead>
        <tbody id="tableBody"></tbody>
    </table>

    <div class="print-footer">
        <p>Generated by FuelingSys ERP - Purchase Reports Module</p>
    </div>

    <script>
        const reportType = '<?php echo $report_type; ?>';
        const dateRange = '<?php echo $date_range; ?>';
        const companyId = '<?php echo $company_id; ?>';
        const currencySymbol = '<?php echo $currency_symbol; ?>';

        const tableHeaders = {
            item: ["Item ID", "Item Name", "Category", "Quantity", "Unit Price", "Total Value", "Supplier"],
            invoice: ["Invoice ID", "Invoice Name", "Category", "Items", "Due Date", "Total Value", "Supplier"],
            category: ["Category ID", "Category Name", "Type", "Items", "Avg. Price", "Total Value", "Suppliers"],
            supplier: ["Supplier ID", "Supplier Name", "Items", "Avg. Price", "Total Value", "Primary Contact"]
        };

        const reportTitles = {
            item: 'Item-wise Purchase Report',
            invoice: 'Invoice-wise Purchase Report',
            category: 'Category-wise Purchase Report',
            supplier: 'Supplier-wise Purchase Report'
        };

        document.getElementById('reportTitle').textContent = reportTitles[reportType];
        document.getElementById('reportType').textContent = reportTitles[reportType];
        document.getElementById('dateRange').textContent = dateRange;

        // Fetch and display data
        let url = `../../../../server/api/purchase/purchase_reports/purchase-reports.php?type=${reportType}&date_range=${dateRange}`;
        if (companyId) url += `&company_id=${companyId}`;
        
        fetch(url)
            .then(response => response.json())
            .then(result => {
                if (result.success) {
                    renderTable(result.data);
                    setTimeout(() => window.print(), 500);
                }
            });

        function renderTable(data) {
            const tableHead = document.getElementById('tableHead');
            const tableBody = document.getElementById('tableBody');

            // Render headers
            const headerRow = document.createElement('tr');
            tableHeaders[reportType].forEach(header => {
                const th = document.createElement('th');
                th.textContent = header;
                headerRow.appendChild(th);
            });
            tableHead.appendChild(headerRow);

            // Render data
            data.forEach(item => {
                const row = document.createElement('tr');
                let cells = [];

                if (reportType === 'item') {
                    cells = [item.id, item.name, item.category, item.quantity, item.unitPrice, item.total, item.supplier];
                } else if (reportType === 'invoice') {
                    cells = [item.id, item.name, item.category, item.quantity, item.dueDate, item.total, item.supplier];
                } else if (reportType === 'category') {
                    cells = [item.id, item.name, item.category, item.quantity, item.unitPrice, item.total, item.supplier];
                } else if (reportType === 'supplier') {
                    cells = [item.id, item.name, item.quantity, item.unitPrice, item.total, item.contact];
                }

                cells.forEach(cellContent => {
                    const td = document.createElement('td');
                    td.textContent = cellContent;
                    row.appendChild(td);
                });

                tableBody.appendChild(row);
            });
        }
    </script>
</body>
</html>
